apiVersion: kafka.strimzi.io/v1beta2  # see https://strimzi.io/
kind: Kafka # defines a Kafka cluster (specific kind in strimzi)
metadata:
  name: kafka
  namespace: kafka-namespace
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV0
    listeners:
      - name: plain
        port: 29092
        type: internal
        tls: false    # no Authentication
    # Default Kafka configuration for all new topics
    config:
      offsets.topic.replication.factor: 3
      default.replication.factor: 3
      min.insync.replicas: 2
      log.retention.hours: 168
    # Resources applied to all nodes in the pool
    resources:
      requests:
        memory: 1000Mi
        cpu: 500m
      limits:
        memory: 1500Mi
        cpu: 700m
    jvmOptions:
      -Xms: 512m
      -Xmx: 768m
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
    userOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool # defines a group of Kafka nodes (specific kind in strimzi)
metadata:
  name: dual-role
  namespace: kafka-namespace
  labels:
    strimzi.io/cluster: kafka # Links to the Kafka resource above
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod # "Just a Bunch Of Disks" - can have multiple volumes
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
        class: linode-block-storage-retain
        kraftMetadata: shared